#this docker-compose file is for installing mysql:8.0.26 on eclipse onsoil server

networks:
  network-mysql:
    driver: bridge
services:
  mysql-server:
    container_name: mysql_server
    restart: always
    image: mysql:8.0.26
    networks:
      - network-mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin, --default-authentication-plugin=mysql_native_password]
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_config/my.cnf:/etc/mysql/my.cnf
secrets:
   db_root_password:
     file: /root/db_root_password.txt
